apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: sodimac-java
metadata:
  annotations:
    description: Apache Camel for Sodimac.
    iconClass: icon-rh-integration
    openshift.io/display-name: Sodimac Development with Apache Camel
    openshift.io/provider-display-name: Sodimac.
    tags: ApacheCamel
    version: "1"
  name: sodimac-camel
  namespace: #{System.ProjectDev}#
objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      annotations:
        app.openshift.io/vcs-ref: #{BRANCH_DEV}#
        app.openshift.io/vcs-uri: #{System.Repo}#
        sod.contacto-solucion: "Rodolfo Plazas rlopezp@homecenter.co"
        sod.gerencia: #{Gerencia}#
        sod.fecha-creacion: "01-04-2024"
        sod.celula: #{Celula}#
        sod.proyecto: "Migracion Fuse"
        sod.ambiente: #{Ambiente}#
        sod.descripcion-api: "Servicio para extraer los datos del topico Kafka"
        sod.aplicacion: #{System.ServiceName}#
      generation: 3
      labels:
        app: #{System.ServiceName}#
        app.kubernetes.io/component: #{System.ServiceName}#
        app.kubernetes.io/instance: #{System.ServiceName}#
        app.kubernetes.io/part-of: #{System.Application}#
      name: #{System.ServiceName}#
      namespace: #{System.ProjectDev}#
    spec:
      replicas: 1
      selector:
        app: #{System.ServiceName}#
        deploymentconfig: #{System.ServiceName}#
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 120
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: #{System.ServiceName}#
            deploymentconfig: #{System.ServiceName}#
          annotations:
            app.openshift.io/runtime: quarkus
        spec:
          containers:
            - image: image-registry.openshift-image-registry.svc:5000/#{System.ProjectDev}#/#{System.ServiceName}#:#{Build.BuildId}#
              env:
                - name: APPLICATION_NAME
                  value: '#{APPLICATION_NAME}#'
                - name: CONSUMIDOR_AMQS_TOPIC
                  value: '#{CONSUMIDOR_AMQS_TOPIC}#'
                - name: CONSUMIDOR_AMQS_BROKER
                  value: '#{CONSUMIDOR_AMQS_BROKER}#'
                - name: CONSUMIDOR_AMQS_GROUP_ID
                  value: '#{CONSUMIDOR_AMQS_GROUP_ID}#'
                - name: CONSUMIDOR_AMQS_JAAS_CONFIG
                  value: '#{CONSUMIDOR_AMQS_JAAS_CONFIG}#'
                - name: CONSUMIDOR_AMQS_TRUSTSTORE_LOCATION
                  value: '#{CONSUMIDOR_AMQS_TRUSTSTORE_LOCATION}#'
                - name: CONSUMIDOR_AMQS_TRUSTSTORE_PASSWORD
                  value: '#{CONSUMIDOR_AMQS_TRUSTSTORE_PASSWORD}#'
                - name: ENDPOINT_BACKEND_SAPS
                  value: '#{ENDPOINT_BACKEND_SAPS}#'
                - name: TIMEOUT_VARIABLE
                  value: '#{TIMEOUT_VARIABLE}#'
                - name: MEMORY_REQUEST
                  value: #{MEMORY_REQUEST}#
                - name: CPU_REQUEST
                  value: #{CPU_REQUEST}#
                - name: MEMORY_LIMITS
                  value: #{MEMORY_LIMITS}#
                - name: CPU_LIMITS
                  value: #{CPU_LIMITS}#
              imagePullPolicy: Always
              name: #{System.ServiceName}#
             # resources:
             #   limits:
             #     cpu: #{CPU_LIMITS}#
             #     memory: #{MEMORY_LIMITS}#
             #   requests:
             #     cpu: #{CPU_REQUEST}#
             #     memory: #{MEMORY_REQUEST}#
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        app.openshift.io/vcs-ref: #{BRANCH_DEV}#
        app.openshift.io/vcs-uri: #{System.Repo}#
      labels:
        app: #{System.ServiceName}#
        app.kubernetes.io/component: #{System.ServiceName}#
        app.kubernetes.io/instance: #{System.ServiceName}#
        app.kubernetes.io/part-of: #{System.ServiceName}#
      name: #{System.ServiceName}#
      namespace: #{System.ProjectDev}#
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        app: #{System.ServiceName}#
        deploymentconfig: #{System.ServiceName}#
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Route
    metadata:
      annotations:
        app.openshift.io/vcs-ref: #{BRANCH_DEV}#
        app.openshift.io/vcs-uri: #{System.Repo}#
        openshift.io/host.generated: "true"
        haproxy.router.openshift.io/timeout: 300000ms
        haproxy.router.openshift.io/hsts_header: max-age=31536000
      labels:
        app: #{System.ServiceName}#
        app.kubernetes.io/component: #{System.ServiceName}#
        app.kubernetes.io/instance: #{System.ServiceName}#
        app.kubernetes.io/part-of: #{System.ServiceName}#
      name: #{System.ServiceName}#
      namespace: #{System.ProjectDev}#
    spec:
      host: #{System.ServiceName}#-#{System.ProjectDev}#.apps.openshiftqa.sodimacpr.corp
      port:
        targetPort: 8080-tcp
      subdomain: ""
      to:
        kind: Service
        name: #{System.ServiceName}#
        weight: 100
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
#  - apiVersion: autoscaling/v2beta2
#    kind: HorizontalPodAutoscaler
#    metadata:
#      name: hpa-#{System.ServiceName}#
#      namespace: #{System.ProjectDev}#
#    spec:
#      behavior:
#        scaleDown:
#          policies:
#          - type: Pods
#            value: 1
#            periodSeconds: 15
#          - type: Percent
#            value: 100
#            periodSeconds: 15
#          selectPolicy: Min
#          stabilizationWindowSeconds: 0
#        scaleUp:
#          policies:
#          - type: Pods
#            value: 1
#            periodSeconds: 15
#          - type: Percent
#            value: 100
#            periodSeconds: 15
#          selectPolicy: Max
#          stabilizationWindowSeconds: 0
#      scaleTargetRef:
#        kind: DeploymentConfig
#        name: #{System.ServiceName}#
#        apiVersion: apps.openshift.io/v1
#      minReplicas: 1
#      maxReplicas: 4
#      metrics:
#        - type: Resource
#          resource:
#            name: cpu
#            target:
#              type: Utilization
#              averageUtilization: 30
#        - type: Resource
#          resource:
#            name: memory
#            target:
#              type: Utilization
#              averageUtilization: 30